language: generic
os: osx
osx_image: xcode9
branches:
  only:
  - master
before_install:
- export XCODEBUILD_PATH=$(which xcodebuild)
- export PATH=$PATH:$XCODEBUILD_PATH
- export PATH=$PATH:~/bin
- brew update
- gem install xcpretty --user-install --no-rdoc --no-ri-n~/bin
- gem install fastlane --no-rdoc --no-ri --user-install -n~/bin
install:
- xcrun simctl list
- carthage update --platform 'iOS' 
- carthage update --platform 'tvOS' 
script:
- ./test
